sap.ui.define([], function () {
	"use strict";
	var eventos =
		{
			INDIC_PROPIEDAD_PROPIOS: "P",
			INDIC_PROPIEDAD_TERCEROS: "T",
			TIPOEVENTOCALA: "3",
			TIPOEVENTODESCARGA: "6",
			TIPOEVENTOSINIESTRO: "8",
			TIPOEVENTOACCIDENTE: "9",
			TIPOEVENTOZARPE: "1",
			TIPOEVENTOLLEGADAZONA: "2",
			TIPOEVENTOESPERA: "7",
			TIPOEVENTOARRIBOPUE: "5",
			TIPOEVENTOSALIDAZONA: "4",
			TIPOEVENTOHOROMETRO: "H",
			TIPOEVENTOTRASVASE: "T"
			
		}

	return eventos;
});